name: Setup

inputs:
  runs-on:
    type: string
    required: true
    default: ubuntu-latest

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install wine64 for windows
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wine64
      if: ${{ inputs.runs-on == 'ubuntu-latest' }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn --frozen-lockfile
