name: Base64 to file

on:
  workflow_call:
    inputs:
      dist:
        required: true
        type: string
    secrets:
      base64:
        required: true
        type: string

runs:
  using: composite
  steps:
    - run: |
        echo "${{ secrets.base64 }}" > ${{ github.workspace }}/tmp.base64
        certutil -f -decode ${{ github.workspace }}/tmp.base64 ${{ inputs.dist }}
