name: Desktop

on:
  push:
    branches:
      - '**'
    paths:
      - 'desktop/**'
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desktop
    steps:
      - name: Echo
        run: echo "Changed desktop"

