name: Desktop Release

on:
  push:
    branches: [ main ]
    # paths: [ 'desktop/**' ]
  workflow_dispatch:

defaults:
  run:
    working-directory: desktop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install wine64 for windows
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wine64

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Create env file for production
      run: |
        touch .env.production
        echo "NODE_ENV=production" >> .env.production
        echo "REACT_APP_GROUP_ID=2" >> .env.production
        echo "REACT_APP_API_ORIGIN='http://ias1-staging1-srvus-pub-alb-1167594217.ap-northeast-1.elb.amazonaws.com'" >> .env.production
        echo "REACT_APP_AUTH_REGION=${{ secrets.COGNITO_AUTH_REGION }}" >> .env.production
        echo "REACT_APP_AUTH_USER_POOL_ID=${{ secrets.COGNITO_AUTH_USER_POOL_ID }}" >> .env.production
        echo "REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID=${{ secrets.COGNITO_AUTH_USER_POOL_WEB_CLIENT_ID }}" >> .env.production

    - name: Create env file for staging
      run: |
        touch .env.staging
        echo "NODE_ENV=staging" >> .env
        echo "REACT_APP_GROUP_ID=2" >> .env.staging
        echo "REACT_APP_API_ORIGIN='http://ias1-staging1-srvus-pub-alb-1167594217.ap-northeast-1.elb.amazonaws.com'" >> .env.staging
        echo "REACT_APP_AUTH_REGION=${{ secrets.STAGE_COGNITO_AUTH_REGION }}" >> .env.staging
        echo "REACT_APP_AUTH_USER_POOL_ID=${{ secrets.STAGE_COGNITO_AUTH_USER_POOL_ID }}" >> .env.staging
        echo "REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID=${{ secrets.STAGE_COGNITO_AUTH_USER_POOL_WEB_CLIENT_ID }}" >> .env.staging

    - name: Package release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release --debug
