name: Reusable Desktop Release Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: staging
      runs-on:
        type: string
        required: true
        default: ubuntu-latest
      group_id:
        type: string
        required: true
      api_origin:
        type: string
        required: true
    secrets:
      cognito_auth_region:
        required: true
      cognito_auth_user_pool_id:
        required: true
      cognito_auth_user_pool_web_client_id:
        required: true

defaults:
  run:
    working-directory: desktop

jobs:
  release:
    name: Release
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install wine64 for windows
        run: |
          sudo apt-get -y update
          sudo apt-get -y install wine64
        if: ${{ inputs.runs-on == 'ubuntu-latest' }}
      - name: 'Create env file'
        run: |
          touch .env
          echo "REACT_APP_GROUP_ID=${{ inputs.group_id }}" >> .env
          echo "REACT_APP_API_ORIGIN='${{ inputs.api_origin }}'" >> .env
          echo "REACT_APP_AUTH_REGION=${{ secrets.cognito_auth_region }}" >> .env
          echo "REACT_APP_AUTH_USER_POOL_ID=${{ secrets.cognito_auth_user_pool_id }}" >> .env
          echo "REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID=${{ secrets.cognito_auth_user_pool_web_client_id }}" >> .env
      - run: cat .env
      - run: ls -la ./
      - run: ls -la ../
      - name: Release
        env:
          NODE_ENV: ${{ inputs.environment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug
