name: UI

on:
  push:
    branches:
      - '**'
    paths:
      - 'ui/**'
      - 'desktop/**'
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desktop
    steps:
      - name: Desktop Echo
        run: echo "Changed desktop"
        if: steps.filter.outputs.desktop == 'true'
      - name: UI Echo
        run: echo "Changed ui"
        if: steps.filter.outputs.ui == 'true'
