name: Desktop make

on:
  workflow_dispatch:
    inputs:
      windows_pfx_file:
        required: true
      windows_pfx_password:
        required: true

defaults:
  run:
    working-directory: desktop

jobs:
  make:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - run: echo "::add-mask::${{ inputs.windows_pfx_file }}"
      - run: echo "::add-mask::${{ inputs.windows_pfx_password }}"

      - name: Create certificate file
        run: |
          echo "${{ inputs.windows_pfx_file }}" > ${{ github.workspace }}/certificate.base64
          certutil -f -decode ${{ github.workspace }}/certificate.base64 ${{ github.workspace }}/certificate.pfx

      - name: Build
        env:
          REACT_APP_GROUP_ID: 2
          REACT_APP_API_ORIGIN: 'http://ias1-staging1-srvus-pub-alb-1167594217.ap-northeast-1.elb.amazonaws.com'
          REACT_APP_AUTH_REGION: ${{ secrets.COGNITO_AUTH_REGION }}
          REACT_APP_AUTH_USER_POOL_ID: ${{ secrets.COGNITO_AUTH_USER_POOL_ID }}
          REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID: ${{ secrets.COGNITO_AUTH_USER_POOL_WEB_CLIENT_ID }}
          WINDOWS_PFX_FILE: ${{ github.workspace }}/certificate.pfx
          WINDOWS_PFX_PASSWORD: ${{ inputs.windows_pfx_password }}
        run: yarn make:win

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/releases/uploader-ui/')
        with:
          files: |
            desktop/out/make/squirrel.windows/x64/*.exe
