name: Release Windows Installer

on:
  workflow_dispatch:
    inputs:
      windows_pfx_file:
        description: コード証明書 (Base64エンコードした文字列)
        required: true
        type: string
      windows_pfx_password:
        description: コード証明書のパスワード
        required: true
        type: string

defaults:
  run:
    working-directory: desktop

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Set inputs mask
        run: |
          npm install -g node-jq --ignore-scripts
          INPUT_WINDOWS_PFX_BASE64=$(jq -r '.inputs.windows_pfx_file' $GITHUB_EVENT_PATH)
          INPUT_WINDOWS_PFX_PASSWORD=$(jq -r '.inputs.windows_pfx_password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$INPUT_WINDOWS_PFX_BASE64
          echo ::add-mask::$INPUT_WINDOWS_PFX_PASSWORD
          echo WINDOWS_PFX_BASE64="$INPUT_WINDOWS_PFX_BASE64" >> $GITHUB_ENV
          echo WINDOWS_PFX_PASSWORD="$INPUT_WINDOWS_PFX_PASSWORD" >> $GITHUB_ENV
        shell: bash

      - name: Create certificate file
        run: |
          echo "${{ env.WINDOWS_PFX_BASE64 }}" > ${{ github.workspace }}/tmp.base64
          certutil -f -decode ${{ github.workspace }}/tmp.base64 ${{ github.workspace }}/certificate.pfx

      - name: Build
        env:
          REACT_APP_GROUP_ID: 2
          REACT_APP_API_ORIGIN: 'http://ias1-staging1-srvus-pub-alb-1167594217.ap-northeast-1.elb.amazonaws.com'
          REACT_APP_AUTH_REGION: ${{ secrets.COGNITO_AUTH_REGION }}
          REACT_APP_AUTH_USER_POOL_ID: ${{ secrets.COGNITO_AUTH_USER_POOL_ID }}
          REACT_APP_AUTH_USER_POOL_WEB_CLIENT_ID: ${{ secrets.COGNITO_AUTH_USER_POOL_WEB_CLIENT_ID }}
          WINDOWS_PFX_FILE: ${{ github.workspace }}/certificate.pfx
          WINDOWS_PFX_PASSWORD: ${{ env.WINDOWS_PFX_PASSWORD }}
        run: yarn make:win

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/releases/uploader-ui/')
        with:
          files: |
            desktop/out/make/squirrel.windows/x64/*.exe
